### ISSUE TITLE
Refatorar o repositório: separar implementação de análise

### ISSUE THREAD

**Issue by ryukinix** [datascience-ufc/asd#11]
Há alguns procedimentos que devem estar contidos no software e não em notebooks. Notebooks é apenas para análise e exploração, o resultado final deve estar contido na nossa biblioteca/software sendo desenvolvida! JUPYTER NOTEBOOKS NÃO SÃO FINS DE CONSTRUÇÃO DE SOFTWARE.

**Comment by matheus-frota** [comment]
@ryukinix vou começar a refatorar o repositório!
